import type { Rental } from "@/validators/rental.validator"

export const mockRentals: Rental[] = [
  {
    id: "r001",
    rentalID: 1,
    product: "Medical Equipment 2024",
    vendor: "MedEquip Solutions",
    user: {
      id: "u001",
      name: "John Doe Healthcare",
      email: "john@healthcare.com",
      mobileNumber: 12345678900,
    //   company: "Healthcare Solutions Inc.",
    },
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    duration: {
      durationType: "daily",
      durationValue: 28,
    },
    invoiceAddress: {
      addressLine1: "123 Healthcare St",
      street: "Medical District",
      pincode: "12345",
      city: "City",
      state: "State",
    },
    deliveryAddress: {
      addressLine1: "456 Hospital Ave",
      street: "Medical Center",
      pincode: "12345",
      city: "City",
      state: "State",
    },
    status: "Quotation",
    products: [
      {
        product: {
          id: "p001",
          name: "Premium Wheelchair",
          description: "High-quality medical wheelchair",
        },
        quantity: 5,
        price: 200,
      },
      {
        product: {
          id: "p002",
          name: "Hospital Bed",
          description: "Adjustable hospital bed",
        },
        quantity: 2,
        price: 350,
      },
    ],
    amount: 1700,
    tax: 0,
    couponCode: null,
    couponDiscount: 0,
    totalAmt: 1700,
  },
  {
    id: "r002",
    rentalID: 2,
    product: "Surgical Equipment Package",
    vendor: "SurgiTech Pro",
    user: {
      id: "u002",
      name: "Sarah Wilson Medical",
      email: "sarah@wilsonmedical.com",
      mobileNumber: 5551234567,
    //   company: "Wilson Medical Center",
    },
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-03-15"),
    duration: {
      durationType: "monthly",
      durationValue: 2,
    },
    invoiceAddress: {
      addressLine1: "789 Medical Plaza",
      street: "Healthcare District",
      pincode: "54321",
      city: "Metro City",
      state: "California",
    },
    deliveryAddress: {
      addressLine1: "789 Medical Plaza",
      street: "Healthcare District",
      pincode: "54321",
      city: "Metro City",
      state: "California",
    },
    status: "Reserved",
    products: [
      {
        product: {
          id: "p003",
          name: "Surgical Monitor",
          description: "Advanced patient monitoring system",
        },
        quantity: 3,
        price: 800,
      },
      {
        product: {
          id: "p004",
          name: "Ventilator",
          description: "ICU grade ventilator",
        },
        quantity: 1,
        price: 1500,
      },
    ],
    amount: 3900,
    tax: 390,
    couponCode: "MEDICAL10",
    couponDiscount: 390,
    totalAmt: 3900,
  },
  {
    id: "r003",
    rentalID: 3,
    product: "Rehabilitation Equipment",
    vendor: "RehabTech Solutions",
    user: {
      id: "u003",
      name: "Michael Chen Therapy",
      email: "michael@chentherapy.com",
      mobileNumber: 17778889999,
    //   company: "Chen Physical Therapy",
    },
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    duration: {
      durationType: "daily",
      durationValue: 30,
    },
    invoiceAddress: {
      addressLine1: "456 Therapy Lane",
      street: "Wellness District",
      pincode: "67890",
      city: "Healthville",
      state: "Texas",
    },
    deliveryAddress: {
      addressLine1: "456 Therapy Lane",
      street: "Wellness District",
      pincode: "67890",
      city: "Healthville",
      state: "Texas",
    },
    status: "Picked Up",
    products: [
      {
        product: {
          id: "p005",
          name: "Exercise Bike",
          description: "Medical grade exercise bicycle",
        },
        quantity: 2,
        price: 300,
      },
      {
        product: {
          id: "p006",
          name: "Therapy Table",
          description: "Adjustable therapy treatment table",
        },
        quantity: 1,
        price: 450,
      },
    ],
    amount: 1050,
    tax: 105,
    couponCode: null,
    couponDiscount: 0,
    totalAmt: 1155,
  },
  {
    id: "r004",
    rentalID: 4,
    product: "Diagnostic Equipment Set",
    vendor: "DiagnoTech Inc",
    user: {
      id: "u004",
      name: "Lisa Rodriguez Clinic",
      email: "lisa@rodriguezclinic.com",
      mobileNumber: 13334445555,
    //   company: "Rodriguez Family Clinic",
    },
    startDate: new Date("2023-12-01"),
    endDate: new Date("2024-01-15"),
    duration: {
      durationType: "daily",
      durationValue: 45,
    },
    invoiceAddress: {
      addressLine1: "321 Clinic Road",
      street: "Medical Park",
      pincode: "98765",
      city: "Medtown",
      state: "Florida",
    },
    deliveryAddress: {
      addressLine1: "321 Clinic Road",
      street: "Medical Park",
      pincode: "98765",
      city: "Medtown",
      state: "Florida",
    },
    status: "Delivered",
    products: [
      {
        product: {
          id: "p007",
          name: "X-Ray Machine",
          description: "Portable digital X-ray system",
        },
        quantity: 1,
        price: 2500,
      },
      {
        product: {
          id: "p008",
          name: "Ultrasound Device",
          description: "Handheld ultrasound scanner",
        },
        quantity: 1,
        price: 1800,
      },
    ],
    amount: 4300,
    tax: 430,
    couponCode: "CLINIC15",
    couponDiscount: 645,
    totalAmt: 4085,
  },
  {
    id: "r005",
    rentalID: 5,
    product: "Emergency Equipment Kit",
    vendor: "EmergencyMed Supply",
    user: {
      id: "u005",
      name: "David Park Emergency",
      email: "david@parkemergency.com",
      mobileNumber: 16667778888,
    //   company: "Park Emergency Services",
    },
    startDate: new Date("2023-11-01"),
    endDate: new Date("2023-12-31"),
    duration: {
      durationType: "monthly",
      durationValue: 2,
    },
    invoiceAddress: {
      addressLine1: "654 Emergency Blvd",
      street: "First Response District",
      pincode: "13579",
      city: "Urgentville",
      state: "New York",
    },
    deliveryAddress: {
      addressLine1: "654 Emergency Blvd",
      street: "First Response District",
      pincode: "13579",
      city: "Urgentville",
      state: "New York",
    },
    status: "Returned",
    products: [
      {
        product: {
          id: "p009",
          name: "Defibrillator",
          description: "Automated external defibrillator",
        },
        quantity: 2,
        price: 1200,
      },
      {
        product: {
          id: "p010",
          name: "Emergency Stretcher",
          description: "Lightweight emergency transport stretcher",
        },
        quantity: 3,
        price: 400,
      },
    ],
    amount: 3600,
    tax: 360,
    couponCode: null,
    couponDiscount: 0,
    totalAmt: 3960,
  },
]

// Keep the original single rental for backward compatibility
export const mockRental: Rental = mockRentals[0]
